#!/bin/bash

set -eu

TAG=$1
REPO=kunst1080/x11-wm
CONTAINER=$REPO:$TAG

docker run --rm -it --privileged \
	-v /run/udev:/run/udev \
	-v /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket \
	-v /etc/localtime:/etc/localtime:ro \
	-v /usr/lib/locale/locale-archive:/usr/lib/locale/locale-archive:ro \
    -e LANG=$LANG \
    $CONTAINER \
	$*
