#!/bin/bash

set -u

usage_exit() {
        echo "Usage: $0 [--rm] [-d home-directory] [-u user] [-c command] [tag]" 1>&2
        exit 1
}

option_rm=""
option_mount_home=""
option_user="-u root"
command=""

while getopts d:u:c:-: OPT
do
    case $OPT in
        -)
            case "$OPTARG" in
                rm)   option_rm="--rm"
                ;;
            esac
            ;;
        d)  option_mount_home="-v $OPTARG:/home/user"
            ;;
        u)  option_user="-u $OPTARG"
            ;;
        c)  command="$OPTARG"
            ;;
        \?) usage_exit
            ;;
    esac
done

shift $((OPTIND - 1))

readonly REPO=kunst1080/x11-wm
readonly CONTAINER=$REPO:$1

docker run -it --privileged \
	$option_rm \
	-v /run/udev:/run/udev \
	-v /etc/localtime:/etc/localtime:ro \
	-v /usr/lib/locale/locale-archive:/usr/lib/locale/locale-archive:ro \
    -e LANG=$LANG \
	$option_user \
	$option_mount_home \
	$CONTAINER \
	$command

